classDiagram
    class RoboExplorador {
        -String nome
        -int x
        -int y
        -int bateria
        +mover(int graus, int x, int y)
        +posicao()
        +direcaoAtual()
        +girar(String lado)
    }